driver:
  enabled: false
toolkit:
  enabled: true
dcgmExporter:
  enabled: true
  serviceMonitor: 
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
nodeStatusExporter:
  enabled: true
nfd:
  enabled: true
