apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/s-frw/ml-platform
    targetRevision: HEAD
    path: platform/ci
  destination:
    server: https://kubernetes.default.svc
    namespace: ci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

