apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/s-frw/ml-platform
    targetRevision: HEAD
    path: ml/gpu-job
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
