apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/ml-platform.git
    targetRevision: HEAD
    path: platform/data/postgres
    helm:
      chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.3.0
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pgsql-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true

