prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
    storageSpec:
      storageClassName: local-ssd
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi

alertmanager:
  enabled: true

grafana:
  enabled: true
  adminPassword: admin
  defaultDashboardsEnabled: true
  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

defaultRules:
  create: true
