prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 12h
    storageSpec: null

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage: null

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

