apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/s-frw/ml-platform
    - https://prometheus-community.github.io/helm-charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
 
