apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: sfr1/mlflow:2.9.2
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - -c
            - |
              mlflow server \
              --backend-store-uri=postgresql+psycopg2://mlflow:mlflowpass@postgres-postrgresql.psql-db.svc.cluster.local:5432/mlflow \
              --default-artifact-root=s3://mlflow/ \
              --host=0.0.0.0 \
              --port=5000
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.ml-platform.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: AWS_SECRET_ACCESS_KEY
