apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability

