apiVersion: batch/v1
kind: Job
metadata:
  name: iris-training
  namespace: ml-platform
spec:
  template:
    metadata:
      labels:
        job-name: iris-training
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: sfr1/iris-training:0.1.3
          imagePullPolicy: Always
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.ml-platform.svc.cluster.local:5000
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.ml-platform.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: AWS_SECRET_ACCESS_KEY
          command: ["python"]
          args: ["train.py"]
