apiVersion: batch/v1
kind: Job
metadata:
  name: iris-training
  namespace: platform
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: sfr1/iris-training:0.1.0
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.platform.svc.cluster.local:5000"
